### ISSUE TITLE
file path for require seems to be incorrect

### ISSUE THREAD

**Issue by pbdeuchler** [maksimr/vim-jsbeautify#126]
(installed yesterday)

```js
module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/pdeuchler/workspace/dotfiles/janus/vim-jsbeautify/plugin/lib/js/lib/beautify.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at e (/Users/pdeuchler/Dropbox/workspace/dotfiles/janus/vim-jsbeautify/plugin/beautify.min.js:1:884)
    at /Users/pdeuchler/Dropbox/workspace/dotfiles/janus/vim-jsbeautify/plugin/beautify.min.js:1:1117
    at Object.<anonymous> (/Users/pdeuchler/Dropbox/workspace/dotfiles/janus/vim-jsbeautify/plugin/beautify.min.js:1:1334)
    at Object.<anonymous> (/Users/pdeuchler/Dropbox/workspace/dotfiles/janus/vim-jsbeautify/plugin/beautify.min.js:1:1344)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

And here is the plugin directory tree:
```
14:36:08: /Users/pdeuchler/.janus/vim-jsbeautify/plugin (master) (3) 
 → tree . -L 5
.
├── beautifier.vim
├── beautify.js
├── beautify.min.js
└── lib

1 directory, 3 files
```
FYI I have `/Users/pdeuchler/workspace/dotfiles/janus/` symlinked to `/Users/pdeuchler/.janus/`

**Comment by maksimr** [comment]
@pbdeuchler It's really strange. I have installed latest version of vim-jsbeautify and all work as expected with default config

Thanks

**Comment by pbdeuchler** [comment]
@maksimr yup, seems my submodule update is failing because I have weirdness in my config. Appreciate the help!

**Comment by maksimr** [comment]
@pbdeuchler you are welcome!)
