### ISSUE TITLE
Error: Cannot find module 'd:\Program' with gvim installed in "d:\Program Files (x86)\Vim"

### ISSUE THREAD

**Issue by wangxxi** [maksimr/vim-jsbeautify#68]
module.js:340
    throw err;
          ^
Error: Cannot find module 'd:\Program'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:

could you please help ?

**Comment by lenny0702** [comment]
I also got this issue, my environment is Win 7,  node V 0.10
But my error is a little different in the disk part:
    Error: Cannot find module 'C:\Program' 

and as you say the command
    :echo map(['$HOME/.editorconfig', '$HOME/.vim/.editorconfig'], 'expand(v:val)')
     it's output is 
![image](https://cloud.githubusercontent.com/assets/2850927/5734849/5850ef0c-9bf7-11e4-9e79-59ffe622f065.png)
seems it found the configure file , but still goes wrong. 

hopes you will help me. this plugin is really useful to me, Thanks!

**Comment by maksimr** [comment]
@lenny0702 Thanks for feedback.

Let's try to look at the problem from the top down.
I think error `Error: Cannot find module 'C:\Program'` throw [here](https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautify.js#L68)
`path` we pass from *vim* to *node* [here](https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautifier.vim#L404).
Value for `path` we get [here](https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautifier.vim#L376-L378) and [here](https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautifier.vim#L400) we escape quotes.

It will be cool :+1:  if you try debug from js and find a place where broken path.

**Comment by maksimr** [comment]
I try reproduce it on Windows.

If put plugin to `Program Files/...`(where installed vim) then I get error but if I put it in User home directory($HOME/vimfiles/) then all work correct.

**Comment by lenny0702** [comment]
yes, the problem is the space in file path, I think I kind of figure it out here.
I output your system call for running node.js, as shown below
![image](https://cloud.githubusercontent.com/assets/2850927/5738532/4b65dab0-9c28-11e4-8a15-176ae8d815fc.png)
If you run this in windows command line, you will get the same error which is shown in vim when running you plugin.
![image](https://cloud.githubusercontent.com/assets/2850927/5738579/e76b066a-9c28-11e4-8d0a-55c518b6d55a.png)
I think the problem is that in Windows when your command path include a space , backslash didn't solve the problem, you must keep the whole command in "" like this:
![image](https://cloud.githubusercontent.com/assets/2850927/5738700/270d1226-9c2a-11e4-815d-6ccd11833924.png)
you can try it, may it will solve!
I am still not familiar with your code, will be great if you can fix it

**Comment by maksimr** [comment]
@lenny0702 yup, but quote path is not fully resolve problem because `path` contains slash(`Program\ Files`) which we should remove when we call `system`.
I don't understand how correct resolve path like this now, because manually remove slash is very ugly.

**Comment by maksimr** [comment]
How workaround you can put plugin to `C:\lennylan\vimfiles\plugin\`

**Comment by maksimr** [comment]
Related https://github.com/maksimr/vim-jsbeautify/issues/63

**Comment by lenny0702** [comment]
A little ugly indeed...
But change workaround works fine in my machine, and still, it would be better to fix it, because it's the default path for most window users.
I will investigate it to see if there is a better way to solve it and sync it here
Thanks for the reply.

**Comment by lenny0702** [comment]
A little ugly indeed...
But change workaround works fine in my machine, and still, it would be better to fix it, because it's the default path for most window users.
I will investigate it to see if there is a better way to solve it and sync it here
Thanks for the reply.

**Comment by maksimr** [comment]
@lenny0702 do you use Cygwin?
