### ISSUE TITLE
Error while beautifying

### ISSUE THREAD

**Issue by XadillaX** [maksimr/vim-jsbeautify#78]
```sh
/Users/XadillaX/.vim/bundle/vim-jsbeautify/plugin/beautify.min.js:1
th,options,path){var defOps={indent_size:4,indent_char:" "},content=read(conte
                                                                    ^
TypeError: undefined is not a function
    at /Users/XadillaX/.vim/bundle/vim-jsbeautify/plugin/beautify.min.js:1:1480
    at Object.<anonymous> (/Users/XadillaX/.vim/bundle/vim-jsbeautify/plugin/beautify.min.js:1:1881)
    at Object.<anonymous> (/Users/XadillaX/.vim/bundle/vim-jsbeautify/plugin/beautify.min.js:1:1910)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by maksimr** [comment]
@XadillaX what are you using? (nodejs,iojs or something else)

**Comment by XadillaX** [comment]
@maksimr I've tried both Node.js and IO.js

**Comment by maksimr** [comment]
@XadillaX try run these [checks](https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautify.js#L40-L42) in node repl.

**Comment by XadillaX** [comment]
@maksimr no `global.read` and no `global.load`.

**Comment by maksimr** [comment]
@XadillaX 

```js
global.process && /node(\.exe||js)?$/.test(global.process.execPath)
```

in node repl it return `true`?
Thanks

**Comment by XadillaX** [comment]
```
> global.process.execPath
'/usr/local/bin/iojs'
```

That's it. I used `ivm` and `n`. When I changed it back to `node`, the path is still `iojs`.

**Comment by maksimr** [comment]
@XadillaX ok. In latest version of vim-jsbeautify we [have check](https://github.com/maksimr/vim-jsbeautify/blob/master/plugin/beautify.js#L42) on iojs.
Try update plugin

**Comment by XadillaX** [comment]
@maksimr it works. thx.

**Comment by maksimr** [comment]
@XadillaX no problems!
